config/routes.rb
Railsform::Application.routes.draw do
  resources :items do
    collection do
      get 'search'
    end
  end

  get "/" => "items#index", as: :root

  get "/search" => "items#search", as: :search
  post "/search" => "items#search_results", as: :results

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_one :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  def search
    @type_choices = Type.all.map { |u| [u.title, u.id] }
    @and_n_or = [["OR", "OR"],
                 ["AND", "AND"]]
  end

  def search_results
    @types = Type.all
    @items = Item.all
    @submitted_title = params[:title]
    @submitted_description = params[:description]
    @submitted_type_id = params[:type_id].to_i
    @submitted_owner = params[:owner]
    @operand = params[:orand]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :type_id, :owner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.text_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Item Type</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.type_id %></td>
	<td><%= item.owner %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %> <%= link_to 'Search', search_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/items/search.html.erb
<%= form_tag results_path do %>
    <%= select_tag(:type_id, options_for_select(@type_choices)) %>
  <BR />
    <%= label_tag :title %> <%= text_field_tag :title %>
  <BR />
    <%= label_tag :description %> <%= text_field_tag :description %>
  <BR />
    <%= label_tag :owner %> <%= text_field_tag :owner %>
  <BR />
    <%= select_tag(:orand, options_for_select(@and_n_or)) %>
  <BR />
    <%= submit_tag "Search" %>
<% end %>

app/views/items/search_results.html.erb
<H1>
  Search Results
</H1>

<UL>
  <% @items.select do |item| %>
    <% if(@operand == "AND") %>
      <% item.type_id == @submitted_type_id && %>
      <% item.title == @submitted_title || %>
      <% item.description == @submitted_description || %>
      <% item.owner == @submitted_owner %>
    <% else %>
      <% item.type_id == @submitted_type_id || %>
      <% item.title == @submitted_title || %>
      <% item.description == @submitted_description || %>
      <% item.owner == @submitted_owner %>
    <% end %>
  <% end.each do |item| %>
    <LI>
        <B>Title:</B> <%= item.title %>
      <BR />
        <B>Description:</B> <%= item.description %>
      <BR />
        <B>Type:</B> <%= @types.find(item.type_id).title %>
      <BR />
        <B>Owner:</B> <%= item.owner %>
      <BR />
      <BR />
    </LI>
  <% end %>
</UL>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Type ID:</strong>
  <%= @item.type_id %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @item.owner %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsform</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>